### ISSUE TITLE
Does not respond with 354 on `data`

### ISSUE THREAD

**Issue by JDongian** [amlweems/maildump#1]
<pre>
Connected to lf.lc.
Escape character is '^]'.
data
220 mail.lf.lc ESMTP dumptruck
250 yes sir
DATA
354 fill 'er up
</pre>

You should allow for lower cased commands, since some libraries use this as opposed to the uppercase commands (see python's smtplib.py).

**Comment by amlweems** [comment]
Fixed in #2. Thank.
